### sign in
POST https://bf65e7c30fcf.ngrok.app/auth/login
Content-Type: application/json

{
  "phoneNumber": "+84991234567",
  "password": "supplier"
}


### verify
POST  http://localhost:4000/auth/verify
Content-Type: application/json


